from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("agent_id", description="1 for robot1, 2 for robot2"),
        DeclareLaunchArgument("bind_host", default_value="0.0.0.0"),
        DeclareLaunchArgument("bind_port", default_value=""),
        DeclareLaunchArgument("n_agents", default_value="2"),
        DeclareLaunchArgument("u_bound", default_value="0.08"),
        DeclareLaunchArgument("d_safe", default_value="0.65"),
        DeclareLaunchArgument("formation_margin", default_value="0.15"),
        DeclareLaunchArgument("formation_rotation_rad", default_value="0.0"),
        DeclareLaunchArgument("formation_radius_override", default_value="0.0"),
        DeclareLaunchArgument("safety_warning_radius", default_value="1.20"),
        DeclareLaunchArgument("obstacle_warning_radius", default_value="0.25"),
        DeclareLaunchArgument("d_agent_enter", default_value="0.70"),
        DeclareLaunchArgument("d_agent_exit", default_value="0.75"),
        DeclareLaunchArgument("d_obs_enter", default_value="0.10"),
        DeclareLaunchArgument("d_obs_exit", default_value="0.20"),
        DeclareLaunchArgument("modeC_repulsion_gain_si", default_value="0.90"),
        DeclareLaunchArgument("modeO_target_gain_si", default_value="0.95"),
        DeclareLaunchArgument("modeCO_repulsion_gain_si", default_value="0.90"),
        DeclareLaunchArgument("modeCO_target_gain_si", default_value="0.85"),
        DeclareLaunchArgument("nominal_blend_C_si", default_value="0.35"),
        DeclareLaunchArgument("nominal_blend_O_si", default_value="0.20"),
        DeclareLaunchArgument("nominal_blend_CO_si", default_value="0.15"),
        DeclareLaunchArgument("pair_filter_margin", default_value="0.04"),
        DeclareLaunchArgument("obs_filter_margin", default_value="0.05"),
        DeclareLaunchArgument("filter_projection_passes", default_value="4"),
        DeclareLaunchArgument("obstacles_enabled", default_value="false"),
        DeclareLaunchArgument("obstacle_center_x", default_value="1.0"),
        DeclareLaunchArgument("obstacle_center_y", default_value="-0.33"),
        DeclareLaunchArgument("obstacle_radius", default_value="0.15"),
        DeclareLaunchArgument("obstacle_margin", default_value="0.10"),
        DeclareLaunchArgument("tangential_waypoint_radius", default_value="0.12"),
        DeclareLaunchArgument("orbit_tangent_lookahead", default_value="0.20"),
        Node(
            package="yahboom_2wd_dmpc",
            executable="dmpc_controller_node",
            name=["dmpc_controller_", LaunchConfiguration("agent_id")],
            output="screen",
            arguments=[
                "--agent-id", LaunchConfiguration("agent_id"),
                "--bind-host", LaunchConfiguration("bind_host"),
                "--n-agents", LaunchConfiguration("n_agents"),
                "--model", "single_integrator",
                "--graph", "complete",
                "--auto-M", "false",
                "--M-manual", "5",
                "--u-bound", LaunchConfiguration("u_bound"),
                "--d-safe", LaunchConfiguration("d_safe"),
                "--formation-margin", LaunchConfiguration("formation_margin"),
                "--formation-rotation-rad", LaunchConfiguration("formation_rotation_rad"),
                "--formation-radius-override", LaunchConfiguration("formation_radius_override"),
                "--safety-warning-radius", LaunchConfiguration("safety_warning_radius"),
                "--obstacle-warning-radius", LaunchConfiguration("obstacle_warning_radius"),
                "--d-agent-enter", LaunchConfiguration("d_agent_enter"),
                "--d-agent-exit", LaunchConfiguration("d_agent_exit"),
                "--d-obs-enter", LaunchConfiguration("d_obs_enter"),
                "--d-obs-exit", LaunchConfiguration("d_obs_exit"),
                "--modeC-repulsion-gain-si", LaunchConfiguration("modeC_repulsion_gain_si"),
                "--modeO-target-gain-si", LaunchConfiguration("modeO_target_gain_si"),
                "--modeCO-repulsion-gain-si", LaunchConfiguration("modeCO_repulsion_gain_si"),
                "--modeCO-target-gain-si", LaunchConfiguration("modeCO_target_gain_si"),
                "--nominal-blend-C-si", LaunchConfiguration("nominal_blend_C_si"),
                "--nominal-blend-O-si", LaunchConfiguration("nominal_blend_O_si"),
                "--nominal-blend-CO-si", LaunchConfiguration("nominal_blend_CO_si"),
                "--pair-filter-margin", LaunchConfiguration("pair_filter_margin"),
                "--obs-filter-margin", LaunchConfiguration("obs_filter_margin"),
                "--filter-projection-passes", LaunchConfiguration("filter_projection_passes"),
                "--safety-enabled", "true",
                "--obstacles-enabled", LaunchConfiguration("obstacles_enabled"),
                "--obstacle-center-x", LaunchConfiguration("obstacle_center_x"),
                "--obstacle-center-y", LaunchConfiguration("obstacle_center_y"),
                "--obstacle-radius", LaunchConfiguration("obstacle_radius"),
                "--obstacle-margin", LaunchConfiguration("obstacle_margin"),
                "--tangential-waypoint-radius", LaunchConfiguration("tangential_waypoint_radius"),
                "--orbit-tangent-lookahead", LaunchConfiguration("orbit_tangent_lookahead"),
            ],
        ),
    ])
