from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("robot1_controller_endpoint", default_value="tcp://192.168.178.51:5601"),
        DeclareLaunchArgument("robot2_controller_endpoint", default_value="tcp://192.168.178.52:5602"),
        DeclareLaunchArgument("world_frame", default_value="map"),
        DeclareLaunchArgument("robot1_initial_x", default_value="0.0"),
        DeclareLaunchArgument("robot1_initial_y", default_value="-0.45"),
        DeclareLaunchArgument("robot1_initial_yaw", default_value="0.0"),
        DeclareLaunchArgument("robot2_initial_x", default_value="0.0"),
        DeclareLaunchArgument("robot2_initial_y", default_value="0.45"),
        DeclareLaunchArgument("robot2_initial_yaw", default_value="0.0"),
        DeclareLaunchArgument("enable_motion", default_value="false"),
        DeclareLaunchArgument("rate_hz", default_value="5.0"),
        DeclareLaunchArgument("max_linear_speed", default_value="0.07"),
        DeclareLaunchArgument("max_angular_speed", default_value="0.35"),
        DeclareLaunchArgument("u_bound", default_value="0.08"),
        DeclareLaunchArgument("d_safe", default_value="0.65"),
        DeclareLaunchArgument("formation_margin", default_value="0.15"),
        DeclareLaunchArgument("formation_rotation_rad", default_value="0.0"),
        DeclareLaunchArgument("formation_radius_override", default_value="0.0"),
        DeclareLaunchArgument("safety_warning_radius", default_value="1.20"),
        DeclareLaunchArgument("obstacle_warning_radius", default_value="0.25"),
        DeclareLaunchArgument("d_agent_enter", default_value="0.70"),
        DeclareLaunchArgument("d_agent_exit", default_value="0.75"),
        DeclareLaunchArgument("d_obs_enter", default_value="0.10"),
        DeclareLaunchArgument("d_obs_exit", default_value="0.20"),
        DeclareLaunchArgument("modeC_repulsion_gain_si", default_value="0.90"),
        DeclareLaunchArgument("modeO_target_gain_si", default_value="0.95"),
        DeclareLaunchArgument("modeCO_repulsion_gain_si", default_value="0.90"),
        DeclareLaunchArgument("modeCO_target_gain_si", default_value="0.85"),
        DeclareLaunchArgument("nominal_blend_C_si", default_value="0.35"),
        DeclareLaunchArgument("nominal_blend_O_si", default_value="0.20"),
        DeclareLaunchArgument("nominal_blend_CO_si", default_value="0.15"),
        DeclareLaunchArgument("pair_filter_margin", default_value="0.04"),
        DeclareLaunchArgument("obs_filter_margin", default_value="0.05"),
        DeclareLaunchArgument("filter_projection_passes", default_value="4"),
        DeclareLaunchArgument("obstacles_enabled", default_value="false"),
        DeclareLaunchArgument("obstacle_center_x", default_value="1.0"),
        DeclareLaunchArgument("obstacle_center_y", default_value="-0.33"),
        DeclareLaunchArgument("obstacle_radius", default_value="0.15"),
        DeclareLaunchArgument("obstacle_margin", default_value="0.10"),
        DeclareLaunchArgument("tangential_waypoint_radius", default_value="0.12"),
        DeclareLaunchArgument("orbit_tangent_lookahead", default_value="0.20"),
        DeclareLaunchArgument("formation_hold_enabled", default_value="true"),
        DeclareLaunchArgument("formation_hold_metric", default_value="pairwise"),
        DeclareLaunchArgument("formation_hold_enter_error", default_value="0.04"),
        DeclareLaunchArgument("formation_hold_exit_error", default_value="0.08"),
        DeclareLaunchArgument("formation_hold_min_steps", default_value="2"),
        DeclareLaunchArgument("formation_hold_heading_enabled", default_value="true"),
        DeclareLaunchArgument("formation_hold_heading_gain", default_value="1.0"),
        DeclareLaunchArgument("formation_hold_max_angular_speed", default_value="0.12"),
        DeclareLaunchArgument("formation_hold_heading_tolerance_rad", default_value="0.10"),
        Node(
            package="yahboom_2wd_dmpc",
            executable="dmpc_coordinator_ros_node",
            name="dmpc_coordinator_ros_node",
            output="screen",
            parameters=[{
                "robot_namespaces": ["robot1", "robot2"],
                "agent_ids": [1, 2],
                # Do not pass a LaunchConfiguration list as a STRING_ARRAY.
                # Humble can concatenate substitutions into one scalar string.
                # Pass scalar endpoint parameters and let the node build the list.
                "robot1_controller_endpoint": LaunchConfiguration("robot1_controller_endpoint"),
                "robot2_controller_endpoint": LaunchConfiguration("robot2_controller_endpoint"),
                "world_frame": LaunchConfiguration("world_frame"),
                "robot1_initial_x": LaunchConfiguration("robot1_initial_x"),
                "robot1_initial_y": LaunchConfiguration("robot1_initial_y"),
                "robot1_initial_yaw": LaunchConfiguration("robot1_initial_yaw"),
                "robot2_initial_x": LaunchConfiguration("robot2_initial_x"),
                "robot2_initial_y": LaunchConfiguration("robot2_initial_y"),
                "robot2_initial_yaw": LaunchConfiguration("robot2_initial_yaw"),
                "rate_hz": LaunchConfiguration("rate_hz"),
                "enable_motion": LaunchConfiguration("enable_motion"),
                "model": "single_integrator",
                "graph": "complete",
                "objective_mode": "safe_formation",
                "auto_M": False,
                "M_manual": 5,
                "u_bound": LaunchConfiguration("u_bound"),
                "d_safe": LaunchConfiguration("d_safe"),
                "formation_margin": LaunchConfiguration("formation_margin"),
                "formation_rotation_rad": LaunchConfiguration("formation_rotation_rad"),
                "formation_radius_override": LaunchConfiguration("formation_radius_override"),
                "safety_warning_radius": LaunchConfiguration("safety_warning_radius"),
                "obstacle_warning_radius": LaunchConfiguration("obstacle_warning_radius"),
                "d_agent_enter": LaunchConfiguration("d_agent_enter"),
                "d_agent_exit": LaunchConfiguration("d_agent_exit"),
                "d_obs_enter": LaunchConfiguration("d_obs_enter"),
                "d_obs_exit": LaunchConfiguration("d_obs_exit"),
                "modeC_repulsion_gain_si": LaunchConfiguration("modeC_repulsion_gain_si"),
                "modeO_target_gain_si": LaunchConfiguration("modeO_target_gain_si"),
                "modeCO_repulsion_gain_si": LaunchConfiguration("modeCO_repulsion_gain_si"),
                "modeCO_target_gain_si": LaunchConfiguration("modeCO_target_gain_si"),
                "nominal_blend_C_si": LaunchConfiguration("nominal_blend_C_si"),
                "nominal_blend_O_si": LaunchConfiguration("nominal_blend_O_si"),
                "nominal_blend_CO_si": LaunchConfiguration("nominal_blend_CO_si"),
                "pair_filter_margin": LaunchConfiguration("pair_filter_margin"),
                "obs_filter_margin": LaunchConfiguration("obs_filter_margin"),
                "filter_projection_passes": LaunchConfiguration("filter_projection_passes"),
                "safety_enabled": True,
                "obstacles_enabled": LaunchConfiguration("obstacles_enabled"),
                "obstacle_center_x": LaunchConfiguration("obstacle_center_x"),
                "obstacle_center_y": LaunchConfiguration("obstacle_center_y"),
                "obstacle_radius": LaunchConfiguration("obstacle_radius"),
                "obstacle_margin": LaunchConfiguration("obstacle_margin"),
                "tangential_waypoint_radius": LaunchConfiguration("tangential_waypoint_radius"),
                "orbit_tangent_lookahead": LaunchConfiguration("orbit_tangent_lookahead"),
                "max_linear_speed": LaunchConfiguration("max_linear_speed"),
                "max_angular_speed": LaunchConfiguration("max_angular_speed"),
                "world_command_to_speed_scale": 1.0,
                "heading_gain": 1.8,
                "linear_deadband": 0.005,
                "stop_for_heading_error_rad": 1.20,
                "allow_reverse": False,
                "formation_hold_enabled": LaunchConfiguration("formation_hold_enabled"),
                "formation_hold_metric": LaunchConfiguration("formation_hold_metric"),
                "formation_hold_enter_error": LaunchConfiguration("formation_hold_enter_error"),
                "formation_hold_exit_error": LaunchConfiguration("formation_hold_exit_error"),
                "formation_hold_min_steps": LaunchConfiguration("formation_hold_min_steps"),
                "formation_hold_heading_enabled": LaunchConfiguration("formation_hold_heading_enabled"),
                "formation_hold_heading_gain": LaunchConfiguration("formation_hold_heading_gain"),
                "formation_hold_max_angular_speed": LaunchConfiguration("formation_hold_max_angular_speed"),
                "formation_hold_heading_tolerance_rad": LaunchConfiguration("formation_hold_heading_tolerance_rad"),
            }],
        ),
    ])
