from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def _controller_node(agent_id: str, port: str):
    common_args = [
        "--n-agents", "2",
        "--model", "single_integrator",
        "--graph", "complete",
        "--auto-M", "false",
        "--M-manual", "5",
        "--u-bound", LaunchConfiguration("u_bound"),
        "--d-safe", LaunchConfiguration("d_safe"),
        "--formation-margin", LaunchConfiguration("formation_margin"),
        "--formation-rotation-rad", LaunchConfiguration("formation_rotation_rad"),
        "--formation-radius-override", LaunchConfiguration("formation_radius_override"),
        "--safety-warning-radius", LaunchConfiguration("safety_warning_radius"),
        "--obstacle-warning-radius", LaunchConfiguration("obstacle_warning_radius"),
        "--d-agent-enter", LaunchConfiguration("d_agent_enter"),
        "--d-agent-exit", LaunchConfiguration("d_agent_exit"),
        "--d-obs-enter", LaunchConfiguration("d_obs_enter"),
        "--d-obs-exit", LaunchConfiguration("d_obs_exit"),
        "--modeC-repulsion-gain-si", LaunchConfiguration("modeC_repulsion_gain_si"),
        "--modeO-target-gain-si", LaunchConfiguration("modeO_target_gain_si"),
        "--modeCO-repulsion-gain-si", LaunchConfiguration("modeCO_repulsion_gain_si"),
        "--modeCO-target-gain-si", LaunchConfiguration("modeCO_target_gain_si"),
        "--nominal-blend-C-si", LaunchConfiguration("nominal_blend_C_si"),
        "--nominal-blend-O-si", LaunchConfiguration("nominal_blend_O_si"),
        "--nominal-blend-CO-si", LaunchConfiguration("nominal_blend_CO_si"),
        "--pair-filter-margin", LaunchConfiguration("pair_filter_margin"),
        "--obs-filter-margin", LaunchConfiguration("obs_filter_margin"),
        "--filter-projection-passes", LaunchConfiguration("filter_projection_passes"),
        "--safety-enabled", "true",
        "--obstacles-enabled", LaunchConfiguration("obstacles_enabled"),
        "--obstacle-center-x", LaunchConfiguration("obstacle_center_x"),
        "--obstacle-center-y", LaunchConfiguration("obstacle_center_y"),
        "--obstacle-radius", LaunchConfiguration("obstacle_radius"),
        "--obstacle-margin", LaunchConfiguration("obstacle_margin"),
        "--tangential-waypoint-radius", LaunchConfiguration("tangential_waypoint_radius"),
        "--orbit-tangent-lookahead", LaunchConfiguration("orbit_tangent_lookahead"),
    ]
    return Node(
        package="yahboom_2wd_dmpc",
        executable="dmpc_controller_node",
        name=f"sim_dmpc_controller_{agent_id}",
        output="screen",
        arguments=[
            "--agent-id", agent_id,
            "--bind-host", "0.0.0.0",
            "--bind-port", port,
        ] + common_args,
    )


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("robot1_controller_port", default_value="5701"),
        DeclareLaunchArgument("robot2_controller_port", default_value="5702"),
        DeclareLaunchArgument("robot1_controller_endpoint", default_value="tcp://127.0.0.1:5701"),
        DeclareLaunchArgument("robot2_controller_endpoint", default_value="tcp://127.0.0.1:5702"),
        DeclareLaunchArgument("world_frame", default_value="map"),
        DeclareLaunchArgument("robot1_initial_x", default_value="0.0"),
        DeclareLaunchArgument("robot1_initial_y", default_value="-0.7"),
        DeclareLaunchArgument("robot1_initial_yaw", default_value="0.0"),
        DeclareLaunchArgument("robot2_initial_x", default_value="0.0"),
        DeclareLaunchArgument("robot2_initial_y", default_value="0.7"),
        DeclareLaunchArgument("robot2_initial_yaw", default_value="0.0"),
        DeclareLaunchArgument("enable_motion", default_value="true"),
        DeclareLaunchArgument("sim_rate_hz", default_value="50.0"),
        DeclareLaunchArgument("coordinator_rate_hz", default_value="5.0"),
        DeclareLaunchArgument("max_linear_speed", default_value="0.04"),
        DeclareLaunchArgument("max_angular_speed", default_value="0.20"),
        DeclareLaunchArgument("u_bound", default_value="0.04"),
        DeclareLaunchArgument("d_safe", default_value="0.65"),
        DeclareLaunchArgument("formation_margin", default_value="0.15"),
        DeclareLaunchArgument("formation_rotation_rad", default_value="0.0"),
        DeclareLaunchArgument("formation_radius_override", default_value="0.0"),
        DeclareLaunchArgument("safety_warning_radius", default_value="1.20"),
        DeclareLaunchArgument("obstacle_warning_radius", default_value="0.25"),
        DeclareLaunchArgument("d_agent_enter", default_value="0.70"),
        DeclareLaunchArgument("d_agent_exit", default_value="0.75"),
        DeclareLaunchArgument("d_obs_enter", default_value="0.10"),
        DeclareLaunchArgument("d_obs_exit", default_value="0.20"),
        DeclareLaunchArgument("modeC_repulsion_gain_si", default_value="0.90"),
        DeclareLaunchArgument("modeO_target_gain_si", default_value="0.95"),
        DeclareLaunchArgument("modeCO_repulsion_gain_si", default_value="0.90"),
        DeclareLaunchArgument("modeCO_target_gain_si", default_value="0.85"),
        DeclareLaunchArgument("nominal_blend_C_si", default_value="0.35"),
        DeclareLaunchArgument("nominal_blend_O_si", default_value="0.20"),
        DeclareLaunchArgument("nominal_blend_CO_si", default_value="0.15"),
        DeclareLaunchArgument("pair_filter_margin", default_value="0.04"),
        DeclareLaunchArgument("obs_filter_margin", default_value="0.05"),
        DeclareLaunchArgument("filter_projection_passes", default_value="4"),
        DeclareLaunchArgument("obstacles_enabled", default_value="false"),
        DeclareLaunchArgument("formation_hold_enabled", default_value="true"),
        DeclareLaunchArgument("formation_hold_metric", default_value="pairwise"),
        DeclareLaunchArgument("formation_hold_enter_error", default_value="0.04"),
        DeclareLaunchArgument("formation_hold_exit_error", default_value="0.08"),
        DeclareLaunchArgument("formation_hold_min_steps", default_value="2"),
        DeclareLaunchArgument("formation_hold_heading_enabled", default_value="true"),
        DeclareLaunchArgument("formation_hold_heading_gain", default_value="1.0"),
        DeclareLaunchArgument("formation_hold_max_angular_speed", default_value="0.12"),
        DeclareLaunchArgument("formation_hold_heading_tolerance_rad", default_value="0.10"),
        DeclareLaunchArgument("obstacle_center_x", default_value="1.0"),
        DeclareLaunchArgument("obstacle_center_y", default_value="-0.33"),
        DeclareLaunchArgument("obstacle_radius", default_value="0.15"),
        DeclareLaunchArgument("obstacle_margin", default_value="0.10"),
        DeclareLaunchArgument("tangential_waypoint_radius", default_value="0.12"),
        DeclareLaunchArgument("orbit_tangent_lookahead", default_value="0.20"),
        Node(
            package="yahboom_2wd_dmpc_sim",
            executable="two_robot_sim_node",
            name="two_robot_sim_node",
            output="screen",
            parameters=[{
                "robot_namespaces": ["robot1", "robot2"],
                "rate_hz": LaunchConfiguration("sim_rate_hz"),
                "wheel_radius": 0.0325,
                "wheel_separation": 0.120,
                "encoder_ticks_per_meter": 9000.0,
                "cmd_timeout_s": 0.5,
                "battery_voltage": 12.0,
                "linear_velocity_scale": 1.0,
                "angular_velocity_scale": 1.0,
                "odom_noise_std_xy": 0.0,
                "odom_noise_std_yaw": 0.0,
                "publish_tf": True,
            }],
        ),
        _controller_node("1", LaunchConfiguration("robot1_controller_port")),
        _controller_node("2", LaunchConfiguration("robot2_controller_port")),
        Node(
            package="yahboom_2wd_dmpc",
            executable="dmpc_coordinator_ros_node",
            name="sim_dmpc_coordinator_ros_node",
            output="screen",
            parameters=[{
                "robot_namespaces": ["robot1", "robot2"],
                "agent_ids": [1, 2],
                "robot1_controller_endpoint": LaunchConfiguration("robot1_controller_endpoint"),
                "robot2_controller_endpoint": LaunchConfiguration("robot2_controller_endpoint"),
                "world_frame": LaunchConfiguration("world_frame"),
                "robot1_initial_x": LaunchConfiguration("robot1_initial_x"),
                "robot1_initial_y": LaunchConfiguration("robot1_initial_y"),
                "robot1_initial_yaw": LaunchConfiguration("robot1_initial_yaw"),
                "robot2_initial_x": LaunchConfiguration("robot2_initial_x"),
                "robot2_initial_y": LaunchConfiguration("robot2_initial_y"),
                "robot2_initial_yaw": LaunchConfiguration("robot2_initial_yaw"),
                "rate_hz": LaunchConfiguration("coordinator_rate_hz"),
                "enable_motion": LaunchConfiguration("enable_motion"),
                "model": "single_integrator",
                "graph": "complete",
                "objective_mode": "safe_formation",
                "auto_M": False,
                "M_manual": 5,
                "u_bound": LaunchConfiguration("u_bound"),
                "d_safe": LaunchConfiguration("d_safe"),
                "formation_margin": LaunchConfiguration("formation_margin"),
                "formation_rotation_rad": LaunchConfiguration("formation_rotation_rad"),
                "formation_radius_override": LaunchConfiguration("formation_radius_override"),
                "safety_warning_radius": LaunchConfiguration("safety_warning_radius"),
                "obstacle_warning_radius": LaunchConfiguration("obstacle_warning_radius"),
                "d_agent_enter": LaunchConfiguration("d_agent_enter"),
                "d_agent_exit": LaunchConfiguration("d_agent_exit"),
                "d_obs_enter": LaunchConfiguration("d_obs_enter"),
                "d_obs_exit": LaunchConfiguration("d_obs_exit"),
                "modeC_repulsion_gain_si": LaunchConfiguration("modeC_repulsion_gain_si"),
                "modeO_target_gain_si": LaunchConfiguration("modeO_target_gain_si"),
                "modeCO_repulsion_gain_si": LaunchConfiguration("modeCO_repulsion_gain_si"),
                "modeCO_target_gain_si": LaunchConfiguration("modeCO_target_gain_si"),
                "nominal_blend_C_si": LaunchConfiguration("nominal_blend_C_si"),
                "nominal_blend_O_si": LaunchConfiguration("nominal_blend_O_si"),
                "nominal_blend_CO_si": LaunchConfiguration("nominal_blend_CO_si"),
                "pair_filter_margin": LaunchConfiguration("pair_filter_margin"),
                "obs_filter_margin": LaunchConfiguration("obs_filter_margin"),
                "filter_projection_passes": LaunchConfiguration("filter_projection_passes"),
                "safety_enabled": True,
                "obstacles_enabled": LaunchConfiguration("obstacles_enabled"),
                "obstacle_center_x": LaunchConfiguration("obstacle_center_x"),
                "obstacle_center_y": LaunchConfiguration("obstacle_center_y"),
                "obstacle_radius": LaunchConfiguration("obstacle_radius"),
                "obstacle_margin": LaunchConfiguration("obstacle_margin"),
                "tangential_waypoint_radius": LaunchConfiguration("tangential_waypoint_radius"),
                "orbit_tangent_lookahead": LaunchConfiguration("orbit_tangent_lookahead"),
                "max_linear_speed": LaunchConfiguration("max_linear_speed"),
                "max_angular_speed": LaunchConfiguration("max_angular_speed"),
                "formation_hold_enabled": LaunchConfiguration("formation_hold_enabled"),
                "formation_hold_metric": LaunchConfiguration("formation_hold_metric"),
                "formation_hold_enter_error": LaunchConfiguration("formation_hold_enter_error"),
                "formation_hold_exit_error": LaunchConfiguration("formation_hold_exit_error"),
                "formation_hold_min_steps": LaunchConfiguration("formation_hold_min_steps"),
                "formation_hold_heading_enabled": LaunchConfiguration("formation_hold_heading_enabled"),
                "formation_hold_heading_gain": LaunchConfiguration("formation_hold_heading_gain"),
                "formation_hold_max_angular_speed": LaunchConfiguration("formation_hold_max_angular_speed"),
                "formation_hold_heading_tolerance_rad": LaunchConfiguration("formation_hold_heading_tolerance_rad"),
                "world_command_to_speed_scale": 1.0,
                "heading_gain": 1.8,
                "linear_deadband": 0.005,
                "stop_for_heading_error_rad": 1.20,
                "allow_reverse": False,
            }],
        ),
    ])
